version: '3.8'

services:
  php:
    build: .
    ports:
      - "8086:80"
    depends_on:
      - db
    volumes:
      - .:/var/www/html
    environment:
      DB_HOST: db
      DB_DATABASE: crud_demo
      DB_USERNAME: user
      DB_PASSWORD: userpassword

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: crud_demo
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3333:3306"
    volumes:
      - db-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8083:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: rootpassword
    depends_on:
      - db

volumes:
  db-data:
    driver: local
